### ISSUE TITLE
How to build this app?

### ISSUE THREAD

**Issue by rmj2626** [alinachroma/The-Flight-Search-App#1]
I have cloned the repository, but I have no idea how this application can be built and tested on my emulator or Android Device. Could you please give me some instructions?

**Comment by chroidd** [comment]
Hi! I just tried to clone & run it again, and it worked without issues, can you show what kind of errors are you facing (in the console or so?)

Also, I'm using Android Studio Koala Feature Drop | 2024.1.2, if this helps.

**Comment by rmj2626** [comment]
Sorry Dude, I was trying to build it in vs code using the terminal. But when I tried to run the app in Android Studio Ladybug it worked fine. Great code BTW 😊
